### PR TITLE
Milestone 3

### PR DESCRIPTION
**Pull request by amita-roy**
### In this milestone we have added the mutual friend feature

> A mutual friend link on Users index page
> Mutual friend list in user show page
> Mutual friends works like 
 1. Dodo friend with Pete
 2. Toto friend with Pete
 3. So mutual friend between **Dodo** and **Toto** is Pete

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Great job so far :clap: :clap: :clap:, but you still have some changes :hammer: :wrench: :toolbox: to take care of, take a look at the comments bellow :point_down: :point_down: :point_down: :

- [x]  The friendship should not be created as you did, you need to save one unconfirmed friendship row in the database when the user sends an invitation and then update the status of the friendship when the other user confirms and create the reverse friendship, you were creating both rows in the same time but one was unconfirmed.
here is how you should do it: 
image

- [x] In the User model you should have three types of friendships:
- Friends,
image

- Pending friends,
image

- and friend requests
image

- [x] To get the friends and own posts you don't need to use any logic in your code you can just use a simple query:
#### you code:
image

#### suggestion:
image
 

- [x] A user should be able to cancel a pending friend request.

### Please make all the required changes before you request another code review.
## Happy Coding :tophat:

**Comment by amita-roy** [comment]
We have updated all the code as requested by the TSE and we are thankful to Zakariae El Mejdki (TSE) who helped to implement the changes.

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Hello guys it's me again :wave: :wave: :wave:, glad that you have made the previous request changes :100: :+1: :+1: :fire: I noticed that you generated some other issues on the way, check the comments bellow

- [x] remove all commented code in your project, friendship controller has a comment on the top pls remove it.

- [x] you have an error on your project when I try to add friend nothing happens that's because the friendship is created without specifying the confirmed attribute to false which give it nil and then take no effect on the project, to fix this change ligne 5 on Friendship controller with this line: 
```ruby
    @friendship = current_user.friendships.new(friend_id: params[:user_id], confirmed: false)
```

- [x] I can't see my post when trying to creating one I think you are missing the current user in the posts call.

### Please make all the request changes before you submit another code review.
## Happy Coding :tophat:

**Comment by amita-roy** [comment]
Hi, We have made all the changes as per the review. Thanks

**Review by Rhelli — APPROVED** [review]
# Approved! ✅ 🚀

Hi team, excellent work implementing the previous TSEs requested changes. After setting up your project and having tested it, it all seems to be working and all requested changes have been implemented. Good work! Onto the next milestone!

All the best,

💂🏽 Rory

**Pull request merged**
